### ISSUE TITLE
是不是缺少包了？

### ISSUE THREAD

**Issue by fqtyfz** [ulyn/eos#4]
com.sunsharing.component:resvalidate:jar:1.0.5, 
com.sunsharing.component:utils:jar:1.0.0: Failure

**Comment by ulyn** [comment]
这两个包是内部的包，源码中未提供。
需要的话留个联系方式，可以发给你

**Comment by fqtyfz** [comment]
哦，
wangqianyfz@163.com
非常感谢！

**Comment by clxhhsy** [comment]
您好，可否给我也提供一份，邮箱：clxhhsy@126.com，感谢！

**Comment by clxhhsy** [comment]
@ulyn

**Comment by kandellee** [comment]
求jar包
mickey_nba@126.com
感谢！

**Comment by yinxiaoliang** [comment]
您好，可否给我也提供一份，邮箱：yxl_happy@163.com  , thanks!!

**Comment by wqyxx** [comment]
您好。能给我发一份吗？邮箱：et_wqy@163.com，谢谢！

**Comment by ulyn** [comment]
很抱歉，最近一段时间没上github关注，没及时回复。  
缺少的两个包（eos2）下载地址：http://pan.baidu.com/s/1o7KjPxg
